version: '3'
services:
  upnp:
    restart: unless-stopped:3
    build: .
    image: noxi/docker-upnp-ports:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock